"""initial workspaces docs revisions

Revision ID: 01f91c75b9cf
Revises: 
Create Date: 2026-05-09 17:15:41.298635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '01f91c75b9cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('docs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), server_default='page', nullable=False),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['docs.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docs_parent_id'), 'docs', ['parent_id'], unique=False)
    op.create_index(op.f('ix_docs_updated_at'), 'docs', ['updated_at'], unique=False)
    op.create_index(op.f('ix_docs_workspace_id'), 'docs', ['workspace_id'], unique=False)
    op.create_table('doc_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doc_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['docs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doc_revisions_doc_id'), 'doc_revisions', ['doc_id'], unique=False)
    # ### end Alembic commands ###

    # Postgres FTS: generated tsvector + GIN-индекс для /api/v1/docs/search.
    op.execute("""
        ALTER TABLE docs ADD COLUMN search_tsv tsvector
        GENERATED ALWAYS AS (
            to_tsvector('russian', coalesce(title, '') || ' ' || coalesce(body_md, ''))
        ) STORED
    """)
    op.execute("CREATE INDEX docs_search_tsv_idx ON docs USING GIN (search_tsv)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doc_revisions_doc_id'), table_name='doc_revisions')
    op.drop_table('doc_revisions')
    op.drop_index(op.f('ix_docs_workspace_id'), table_name='docs')
    op.drop_index(op.f('ix_docs_updated_at'), table_name='docs')
    op.drop_index(op.f('ix_docs_parent_id'), table_name='docs')
    op.drop_table('docs')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
